[package]
name = "ika_common"
edition = "2024"
license = "BSD-3-Clause-Clear"
authors = ["dWallet Labs, Ltd. <dev@dwalletlabs.com>"]

























published-at = "0x904ae076bfa38ba880358e7b261d5a51a20fa6313c85f3bb2ab9d8dd48c0be17"
[dependencies]
ika = { local = "../ika" }

[addresses]
ika_common = "0x904ae076bfa38ba880358e7b261d5a51a20fa6313c85f3bb2ab9d8dd48c0be17"

[dev-dependencies]

[dev-addresses]

