[package]
name = "ika"
edition = "2024"
license = "BSD-3-Clause-Clear"
authors = ["dWallet Labs, Ltd. <dev@dwalletlabs.com>"]










published-at = "0xa17d7ffa40ed4902e7fbdbc37b5706368705d0e03700166077f6c0845a1f894a"
[dependencies]

[addresses]
ika = "0xa17d7ffa40ed4902e7fbdbc37b5706368705d0e03700166077f6c0845a1f894a"

[dev-dependencies]

[dev-addresses]

